# modify.py
from __future__ import annotations
from pathlib import Path
from typing import Any


def set_parameter(doc: object, name: str, value: str) -> dict[str, Any]:
    """
    Set a parameter by name, searching UserParameters then ModelParameters.

    Search order:
        1. UserParameters  — engineer-defined, writable
        2. ModelParameters — auto-generated by Inventor features, writable
        3. ReferenceParameters — computed/driven, read-only: raises ValueError
        4. Not found in any collection: raises ValueError

    The Inventor COM .Item() method raises a COM error (not ValueError) when
    an item is not found, so broad `except Exception` in blocks 1 and 2 is safe.

    Args:
        doc:   Open Inventor document object
        name:  Parameter name (case-sensitive)
        value: New expression string, e.g. "150 mm" or "2 * Width"

    Returns:
        Dict with name, old_value, new_value, error=None

    Raises:
        ValueError: If parameter is not found, or is a read-only reference parameter
    """
    params = doc.ComponentDefinition.Parameters

    # 1. Try UserParameters
    try:
        param = params.UserParameters.Item(name)
        old_value = param.Expression
        param.Expression = value
        return {"name": name, "old_value": old_value, "new_value": value, "error": None}
    except Exception:
        pass

    # 2. Try ModelParameters
    try:
        param = params.ModelParameters.Item(name)
        old_value = param.Expression
        param.Expression = value
        return {"name": name, "old_value": old_value, "new_value": value, "error": None}
    except Exception:
        pass

    # 3. Check ReferenceParameters — read-only, give a clear error
    try:
        params.ReferenceParameters.Item(name)
        raise ValueError(
            f"Parameter '{name}' is a read-only reference parameter and cannot be written."
        )
    except ValueError:
        raise   # re-raise the ValueError we just constructed
    except Exception:
        pass    # COM error → name not in ReferenceParameters either

    raise ValueError(f"Parameter '{name}' not found in document")


def set_parameters_batch(
    doc: object,
    changes: dict[str, str],
    raise_on_error: bool = True,
) -> list[dict[str, Any]]:
    """
    Apply multiple parameter changes in one call.

    Args:
        doc: Open Inventor document object
        changes: {parameter_name: new_expression_string}
        raise_on_error: If True, first error raises; if False, errors are collected

    Returns:
        List of result dicts (one per parameter, with optional 'error' key)
    """
    results = []
    for name, value in changes.items():
        try:
            result = set_parameter(doc, name, value)
        except ValueError as e:
            if raise_on_error:
                raise
            result = {"name": name, "old_value": None, "new_value": value, "error": str(e)}
        results.append(result)
    return results


def save_as(doc: object, dest_path: str | Path, save_copy_as: bool = False) -> Path:
    """
    Save the document to a new path via Inventor's SaveAs COM method.

    Args:
        doc: Open Inventor document object
        dest_path: Full destination path (must include filename and extension)
        save_copy_as: Maps directly to Inventor's SaveAs(FileName, SaveCopyAs).
                      False (default) — document object is remapped to the new
                        path; subsequent saves write to the new location.
                      True  — saves a copy; the document object stays mapped to
                        the original path.

    Returns:
        Resolved destination Path
    """
    dest = Path(dest_path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    doc.SaveAs(str(dest), save_copy_as)
    return dest


def open_in_inventor(conn: object, file_path: str | Path) -> object:
    """
    Open an existing file in the connected Inventor instance.

    Args:
        conn: InventorConnection instance (already connected)
        file_path: Path to the file to open

    Returns:
        Opened Document object
    """
    return conn.open_document(str(file_path))
