# modify.py
from __future__ import annotations
from pathlib import Path
from typing import Any


def set_parameter(doc: object, name: str, value: str) -> dict[str, Any]:
    """
    Set a parameter by name, searching UserParameters then ModelParameters.

    Search order:
        1. UserParameters  — engineer-defined, writable
        2. ModelParameters — auto-generated by Inventor features, writable
        3. ReferenceParameters — computed/driven, read-only: raises ValueError
        4. Not found in any collection: raises ValueError

    The Inventor COM .Item() method raises a COM error (not ValueError) when
    an item is not found, so broad `except Exception` in blocks 1 and 2 is safe.

    Args:
        doc:   Open Inventor document object
        name:  Parameter name (case-sensitive)
        value: New expression string, e.g. "150 mm" or "2 * Width"

    Returns:
        Dict with name, old_value, new_value, error=None

    Raises:
        ValueError: If parameter is not found, or is a read-only reference parameter
    """
    params = doc.ComponentDefinition.Parameters

    # 1. Try UserParameters
    try:
        param = params.UserParameters.Item(name)
        old_value = param.Expression
        param.Expression = value
        return {"name": name, "old_value": old_value, "new_value": value, "error": None}
    except Exception:
        pass

    # 2. Try ModelParameters
    try:
        param = params.ModelParameters.Item(name)
        old_value = param.Expression
        param.Expression = value
        return {"name": name, "old_value": old_value, "new_value": value, "error": None}
    except Exception:
        pass

    # 3. Check ReferenceParameters — read-only, give a clear error
    try:
        params.ReferenceParameters.Item(name)
        raise ValueError(
            f"Parameter '{name}' is a read-only reference parameter and cannot be written."
        )
    except ValueError:
        raise   # re-raise the ValueError we just constructed
    except Exception:
        pass    # COM error → name not in ReferenceParameters either

    raise ValueError(f"Parameter '{name}' not found in document")


def set_parameters_batch(
    doc: object,
    changes: dict[str, str],
    raise_on_error: bool = True,
) -> list[dict[str, Any]]:
    """
    Apply multiple parameter changes in one call.

    Args:
        doc: Open Inventor document object
        changes: {parameter_name: new_expression_string}
        raise_on_error: If True, first error raises; if False, errors are collected

    Returns:
        List of result dicts (one per parameter, with optional 'error' key)
    """
    results = []
    for name, value in changes.items():
        try:
            result = set_parameter(doc, name, value)
        except ValueError as e:
            if raise_on_error:
                raise
            result = {"name": name, "old_value": None, "new_value": value, "error": str(e)}
        results.append(result)
    return results


def save_as(doc: object, dest_path: str | Path, save_copy_as: bool = False) -> Path:
    """
    Save the document to a new path via Inventor's SaveAs COM method.

    Args:
        doc: Open Inventor document object
        dest_path: Full destination path (must include filename and extension)
        save_copy_as: Maps directly to Inventor's SaveAs(FileName, SaveCopyAs).
                      False (default) — document object is remapped to the new
                        path; subsequent saves write to the new location.
                      True  — saves a copy; the document object stays mapped to
                        the original path.

    Returns:
        Resolved destination Path
    """
    dest = Path(dest_path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    doc.SaveAs(str(dest), save_copy_as)
    return dest


def open_in_inventor(conn: object, file_path: str | Path) -> object:
    """
    Open an existing file in the connected Inventor instance.

    Args:
        conn: InventorConnection instance (already connected)
        file_path: Path to the file to open

    Returns:
        Opened Document object
    """
    return conn.open_document(str(file_path))


def _find_occurrence(doc: object, occurrence_path: str, app: object) -> tuple:
    """
    Resolve an occurrence by name or slash-separated path.

    Supports both flat names ("part:1") and nested paths ("subassy:1/part:1").
    Returns (occurrence, parent_doc) where parent_doc is the assembly that
    directly contains the occurrence (needed for removal / suppression calls).

    Raises ValueError if any segment of the path is not found.
    """
    segments = occurrence_path.split("/")
    current_doc = doc
    occ = None
    for i, segment in enumerate(segments):
        try:
            occ = current_doc.ComponentDefinition.Occurrences.ItemByName(segment)
        except Exception:
            parent_label = segments[i - 1] if i > 0 else "assembly"
            raise ValueError(
                f"Occurrence '{segment}' not found in '{parent_label}'"
            )
        if i < len(segments) - 1:
            # Navigate into the sub-assembly for the next segment
            current_doc = _get_or_open_sub_doc(occ, app)
    return occ, current_doc


def _get_or_open_sub_doc(occ: object, app: object) -> object:
    """
    Return the sub-document for a ComponentOccurrence.

    Inventor only exposes occ.Definition.Document when the sub-document is
    loaded in memory. If it is unresolved (e.g. Level of Detail = Substitute,
    or file offline), this property raises a COM exception. In that case,
    open the file explicitly via app.Documents.Open().

    Args:
        occ: ComponentOccurrence COM object
        app: Inventor Application COM object (available as conn.app in ToolExecutor)

    Returns:
        The sub-document COM object, loaded if necessary
    """
    try:
        return occ.Definition.Document
    except Exception:
        sub_path = occ.ReferencedDocumentDescriptor.FullDocumentName
        return app.Documents.Open(str(sub_path))


def add_component(
    doc: object,
    app: object,
    file_path: str,
    translation_mm: list[float] | None = None,
) -> dict[str, Any]:
    """
    Add a .ipt or .iam file as a new occurrence in an assembly.

    The occurrence name is assigned automatically by Inventor (e.g. "bracket:1").
    Rotation is not supported in this phase — use identity matrix only.

    Args:
        doc:            Open assembly document object
        app:            Inventor Application object (for TransientGeometry)
        file_path:      Absolute path to the .ipt or .iam file to insert
        translation_mm: Optional [x, y, z] offset from assembly origin in mm.
                        Inventor's internal unit is cm, so values are divided by 10.

    Returns:
        Dict with occurrence_name and file_path

    Note: Matrix.SetTranslation requires a Point (tg.CreatePoint), NOT a Vector
    (tg.CreateVector). Passing a Vector raises a COM type error at runtime.
    """
    tg = app.TransientGeometry
    matrix = tg.CreateMatrix()  # identity matrix
    if translation_mm:
        x, y, z = translation_mm
        pt = tg.CreatePoint(x / 10, y / 10, z / 10)  # mm → cm
        matrix.SetTranslation(pt)
    occ = doc.ComponentDefinition.Occurrences.Add(str(file_path), matrix)
    return {"occurrence_name": occ.Name, "file_path": str(file_path)}


def remove_component(doc: object, occurrence_name: str) -> dict[str, Any]:
    """
    Permanently delete an occurrence from an assembly.

    Irreversible. The agent should confirm intent before calling this.

    Args:
        doc:             Open assembly document object
        occurrence_name: Full occurrence name including :N suffix, e.g. "maincyl:1"

    Returns:
        Dict with {"removed": occurrence_name}

    Raises:
        ValueError: If occurrence_name is not found in the assembly
    """
    try:
        occ = doc.ComponentDefinition.Occurrences.ItemByName(occurrence_name)
    except Exception:
        raise ValueError(f"Occurrence '{occurrence_name}' not found in assembly")
    occ.Delete()
    return {"removed": occurrence_name}


def set_suppressed(doc: object, occurrence_name: str, suppressed: bool) -> dict[str, Any]:
    """
    Suppress or unsuppress a component occurrence.

    Suppressed occurrences are invisible and excluded from BOM and mass calculations.
    Fully reversible — use suppressed=False to restore.

    Args:
        doc:             Open assembly document object
        occurrence_name: Full occurrence name, e.g. "maincyl:1"
        suppressed:      True to suppress, False to unsuppress

    Returns:
        Dict with occurrence_name and suppressed state

    Raises:
        ValueError: If occurrence_name is not found in the assembly
    """
    try:
        occ = doc.ComponentDefinition.Occurrences.ItemByName(occurrence_name)
    except Exception:
        raise ValueError(f"Occurrence '{occurrence_name}' not found in assembly")
    occ.Suppressed = suppressed
    return {"occurrence_name": occurrence_name, "suppressed": suppressed}
